# count all students that live in dormitories, that contain bed bugs

PREFIX ex: <http://example.org/vocabulary/>

SELECT (COUNT(DISTINCT ?student) AS ?studentCount)
WHERE {
  ?student a ex:Student ;
        	ex:staysIn ?dormitory .
  ?dormitory a ex:Dormitory ;
  		    ex:hasBedBugs ?hasBugs .
  FILTER (?hasBugs = true)
}
GROUP BY ?student